export interface IProps {
    id?: number,
    user?: string,
    date?: string,
    createdAt?:string,
    address?: string,
    civiliansWounded?: number,
    civiliansDead?: number,
    agentDead?: number,
    agentWounded?: number,
    description?: string,
    status?:string,
    reprove?: () => void,
    aprove?: () => void,
}